services:
  postgres:
    image: postgres:16-alpine
    container_name: pet-service-postgres
    environment:
      POSTGRES_DB: pet_service
      POSTGRES_USER: pet_service
      POSTGRES_PASSWORD: pet_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pet-service-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  postgres_data: